### ISSUE TITLE
Aktualizacja linków dotyczących informacji o wtyczce

### ISSUE THREAD

**Issue by ksedron** [envirosolutionspl/wtyczka_qgis_app#102]
Zmiana informacji o właścicielu wtyczki APP, dodanie właściwego linku do miejsca publikacji rozporządzenia w sprawie zbiorów danych przestrzennych oraz metadanych w zakresie zagospodarowania przestrzennego (w tym katalogu obiektów) oraz filmów instruktażowych oraz instrukcji użytkownika.

**Comment by ksedron** [comment]
Dodano zaktualizowany banner do wtyczki.

**Comment by envirosolutionspl** [comment]
zrobione

**Comment by KasiaZagrobelna** [comment]
![1_baner](https://user-images.githubusercontent.com/47556554/98118543-aa47b880-1eab-11eb-973e-d6cdc0fcb634.JPG)

Linki są ok. 
Do podmiany jeszcze baner - cały czas wyświetla się poprzedni, mimo, że w plikach wtyczki jest nowy (załączam zrzut).

**Comment by envirosolutionspl** [comment]
poprawione

**Comment by KasiaZagrobelna** [comment]
Przetestowane- baner jest już poprawiony.
