### ISSUE TITLE
Modyfikacja w walidatorze ograniczenia dot. Mapy podkładowej

### ISSUE THREAD

**Issue by ksedron** [envirosolutionspl/wtyczka_qgis_app#104]
Modyfikacja w Walidatorze ograniczenia dotyczącego obligatoryjności mapy podkładowej (Informacje o mapie podkładowej są obligatoryjne dla aktów planowania przestrzennego poziomu lokalnego).

**Comment by envirosolutionspl** [comment]
zrobione - do weryfikacji

**Comment by KasiaZagrobelna** [comment]
Zweryfikowane - jest ok.
