### ISSUE TITLE
Tworzenie/ aktualizacja metadanych - poprawa literówek.

### ISSUE THREAD

**Issue by KasiaZagrobelna** [envirosolutionspl/wtyczka_qgis_app#106]
Przy wczytaniu GML do zakładki tworzenie/aktualizacja metadanych -> sugeruje nazwy zbiorów z literówkami (zrzut dla przypadku GML MPZP).  
![2_metadane nazwa zbioru](https://user-images.githubusercontent.com/47556554/98119137-7caf3f00-1eac-11eb-9481-9363c13805c3.JPG)
Proszę o zmianę sugerowanej przez wtyczkę wartości na "Zbiór danych przestrzennych dla miejscowych planów zagospodarowania przestrzennego <typ_jednostki> <nazwa_jednostki>".

**Comment by KasiaZagrobelna** [comment]
Analogicznie -> dla gml z SUIKZP: 
![3_metadane nazwa zbioru](https://user-images.githubusercontent.com/47556554/98119322-c0a24400-1eac-11eb-9e38-83cb999d7919.JPG)
Proszę o zmianę sugerowanej przez wtyczkę wartości na "Zbiór danych przestrzennych dla studium uwarunkowań i kierunków zagospodarowania przestrzennego gminy <typ_jednostki> <nazwa_jednostki>".

**Comment by KasiaZagrobelna** [comment]
Jeszcze jedna literówka przy komunikacie o błędzie w zakładce "Tworzenie/ aktualizacja metadanych" -> uciekło "ć" na końcu zdania.
<img width="292" alt="4_literowka" src="https://user-images.githubusercontent.com/47556554/98124945-1cbc9680-1eb4-11eb-8ffc-305779220000.PNG">

**Comment by envirosolutionspl** [comment]
poprawione wszystkie 3 przypadki

**Comment by KasiaZagrobelna** [comment]
Sprawdzone -> wszystkie 3 literówki są już poprawione.
