### ISSUE TITLE
[Walidacja zbioru APP] błąd pythona w przypadku braku 'wfs:member'

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/wtyczka_qgis_app#109]
Gdy brak jest tagu wfs:member podczas walidacji występuje błąd pythona

![image](https://user-images.githubusercontent.com/25906739/98558784-2116f400-22a6-11eb-9bf7-38e31af592b4.png)

![image](https://user-images.githubusercontent.com/25906739/98558623-f3ca4600-22a5-11eb-86af-fa793301134d.png)
Wersja wtyczki 1.0

**Comment by KasiaZagrobelna** [comment]
Do poprawy - zbiorcza korekta razem z #107 i #110.

**Comment by envirosolutionspl** [comment]
naprawione w wersji 1.1

**Comment by KasiaZagrobelna** [comment]
Ok
