### ISSUE TITLE
walidacja APP - błędny komunikat o błędnej warstwie przestrzennej

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/wtyczka_qgis_app#110]
W przypadku gdy app:AktPlanowaniaPrzestrzennego jest 2 poziomy poniżej gml:featureMembers/wfs:member wyświetlany jest niepoprawny komunikat:

![image](https://user-images.githubusercontent.com/25906739/98565068-74407500-22ad-11eb-9a8d-65c75bfffa38.png)

**Comment by KasiaZagrobelna** [comment]
Do poprawy - zbiorcza korekta razem z #107 i #109.

**Comment by envirosolutionspl** [comment]
naprawione w wersji 1.1

**Comment by KasiaZagrobelna** [comment]
Ok
