### ISSUE TITLE
Błędna wartość dla atrybutu idIIP

### ISSUE THREAD

**Issue by akiwior** [envirosolutionspl/wtyczka_qgis_app#112]
Wtyczka wyświetla mi Błędna wartość dla atrybutu idIIP. 
dane:
przestrzen Nazwa: 'PL.ZIPPZP.2177/2263011-MPZP'
lokalny Id:  'kotarbinskiego_a'
wersja obiektu : '13.11.2020 00:00'

**Comment by jprzezdziecka** [comment]
W przestrzeni nazw podanej przez Pana numer 2263011 oznacza numer TERYT.
Zgodnie z par. 4 ust. 1 <jpt> oznacza identyfikator jednostki podziału terytorialnego, dla której prowadzony jest zbiór danych
przestrzennych, utworzony na podstawie identyfikatora z rejestru TERYT, **bez ostatniego członu określającego
rodzaj jednostki** -> proszę spróbować zapisać formularz we wtyczce z numerem TERYT = 226301.

**Comment by KasiaZagrobelna** [comment]
Wyjaśnione -> zamykam.
