### ISSUE TITLE
wtyczka nie generuje gml tylko xml

### ISSUE THREAD

**Issue by akiwior** [envirosolutionspl/wtyczka_qgis_app#113]
W kroku 6 z 6 dla APP wtyczka nie generuje pliku gml tylko xml.

**Comment by envirosolutionspl** [comment]
@akiwior wtyczka generuje GML i zapisuje w pliku z rozszerzeniem *.xml

**Comment by akiwior** [comment]
Ta informacja powinna się znaleźć w instrukcji wtyczki.

**Comment by akiwior** [comment]
oraz w samej wtyczce, bo tam wyraźnie 'generuje się plik gml'

**Comment by KasiaZagrobelna** [comment]
Niezależnie od rozszerzenia - to ciągle będzie plik GML.
