### ISSUE TITLE
schemaLocation

### ISSUE THREAD

**Issue by KasiaZagrobelna** [envirosolutionspl/wtyczka_qgis_app#115]
"W pliku GML jest też nadmiarowa spacja w atrybucie xsi:schemaLocation w tagu xsi:schemaLocation w adresie zasobu tj: "https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0 planowaniePrzestrzenne.xsd" "

W przykładowych plikach GML (również w tych generowanych przez wtyczkę) powinno być wskazanie na XSD udostępnione na stronie gov.pl. Poniżej pełna składnia schemaLocation:

xsi:schemaLocation="https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0 https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0/planowaniePrzestrzenne.xsd 
http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd 
http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd"

**Comment by envirosolutionspl** [comment]
poprawione w fbf189a0f4fb78e291217814c7404a1219a026d8

**Comment by KasiaZagrobelna** [comment]
Przetestowane, jest ok.
