### ISSUE TITLE
Błędy podczas wczytania i walidacji pliku metadanych

### ISSUE THREAD

**Issue by KasiaZagrobelna** [envirosolutionspl/wtyczka_qgis_app#116]
Wklejam zgłoszenie od użytkownika: 
"W załączniku przesyłam zrzuty ekranów przedstawiające błędy kodu Python  "Wtyczki APP" w zakresie walidacji pliku metadanych Studium oraz wczytywania istniejącego pliku metadanych. Plik utworzyłem za pomocą  "Wtyczki APP" w wersji 1.1."

Poniżej zip z zrzutem z błędem:

[wtyczka app wczytanie walidacja metadanych.zip](https://github.com/envirosolutionspl/wtyczka_qgis_app/files/5623789/wtyczka.app.wczytanie.walidacja.metadanych.zip)

**Comment by KasiaZagrobelna** [comment]
Przesyłam kolejne info od użytkownika: 
"Dzień dobry,
Naprawiony został tylko jeden z dwóch zgłoszonych błędów.
W formularzu "Tworzenia/aktualizacji metadanych" można co prawda już otworzyć plik metadanych, ale próba jego zapisu i walidacji wywołuje błędy w kodzie Wtyczki APP (por. załącznik).
Formatka "Walidacji GML / XML" poprawnie waliduje plik metadanych."
![Wtyczka-APP-bledy-metadane](https://user-images.githubusercontent.com/47556554/100878333-55975d80-34aa-11eb-88a1-88bfb88aae33.png)

**Comment by envirosolutionspl** [comment]
@KasiaZagrobelna proszę o weryfikację zmian

**Comment by KasiaZagrobelna** [comment]
Przetestowane -> jest ok, zamykam.
