### ISSUE TITLE
Zbiór APP

### ISSUE THREAD

**Issue by weronikaa97** [envirosolutionspl/wtyczka_qgis_app#117]
Z ciekawości po utworzeniu zbioru dla planu miejscowego, otworzyłam wygenerowany zbiór APP w QGisie. Problem w tym, że nie działa przybliżenie do warstwy poligonowej zawierającej obszar planu. Można to uczynić dopiero wtedy, gdy wejdzie się w tabelę atrybutów, zaznaczy tam obiekt i wtedy przybliży się do zaznaczonej warstwy.

**Comment by envirosolutionspl** [comment]
Problem niestety lezy po stronie QGISa. Problem jest tak naprawdę tylko przy przybliżaniu do zasięgu warstwy, zasięgi obiektów są poprawne. Nie wpływa to negatywnie na działanie wtyczki. Problem dotyczy plików GML z definicją układu współrzędnych w formie URI

**Comment by KasiaZagrobelna** [comment]
Taguję i zamykam wątek -> to nie jest błąd wynikający z niepoprawnego działania wtyczki.
