### ISSUE TITLE
Komunikat błędu przy walidacji pliku podpisanego kwalifikowanym podpisem elektronicznym

### ISSUE THREAD

**Issue by KasiaZagrobelna** [envirosolutionspl/wtyczka_qgis_app#118]
Przy próbie walidacji plików podpisanych kwalifikowanym podpisem elektronicznym (podpis wewnętrzny) - wyskakuje błąd z rozpoznaniem bloku z podpisem (moim zdaniem wtyczka powinna go ignorować i robiła tak we wcześniejszych wersjach). Przy ręcznym usunięciu bloku -> walidacja ze schematem jest ok, bo plik sam w sobie jest poprawny. 
W załączeniu przykładowy plik (plus ten edytowany ręcznie) + komunikat o błędzie. 
[blad_signature-2020-12-15.txt](https://github.com/envirosolutionspl/wtyczka_qgis_app/files/5694736/blad_signature-2020-12-15.txt)

**Comment by KasiaZagrobelna** [comment]
[2020-12-15-blad ds_Signature.zip](https://github.com/envirosolutionspl/wtyczka_qgis_app/files/5696655/2020-12-15-blad.ds_Signature.zip)

**Comment by envirosolutionspl** [comment]
@KasiaZagrobelna obecny schemat XSD nie definiuje możliwości użycia podpisu

**Comment by envirosolutionspl** [comment]
Konkretnie zaimplementowany standard OGC nie umożliwia stosowania podpisu cyfrowego.
[https://docs.opengeospatial.org/DRAFTS/19-016.html]
`One other challenge that an OGC Standards Working Group (SWG) should address is the inclusion of a digital signature element in the scheme of a feature collection. Current standards, such as OGC API - Features, do not contain a digital signature as part of the scheme.`

**Comment by envirosolutionspl** [comment]
dodano wyjątek walidacyjny dla podpisu cyfrowego

**Comment by KasiaZagrobelna** [comment]
Przetestowane - działa, zamykam.
