### ISSUE TITLE
Problem z mapą zasadniczą

### ISSUE THREAD

**Issue by 123MR123** [envirosolutionspl/wtyczka_qgis_app#119]
W trakcie tworzenia app dla procedury planistycznej muszę obowiązkowo wypełnić pole zawierające informację o mapie zasadniczej. Na etapie przystąpienia nie mamy jeszcze mapy zasadniczej, zatem pole nie powinno być w ogóle obowiązkowe lub w przypadku procedury powinna być możliwość jego ominięcia.

Pozdrawiam 
Monika Rutyna

**Comment by KasiaZagrobelna** [comment]
Pani Moniko, 
zgodnie z Rozporządzeniem atrybut "mapaPodkładowa" jest obligatoryjny dla planów poziomu lokalnego (np. mpzp). Są to informacje o podkładzie mapowym (którym może być mapa zasadnicza, gdy wymagają tego przepisy), który został użyty do sporządzenia załącznika graficznego do uchwały.

**Comment by 123MR123** [comment]
Załącznik do uchwały **wszczynającej procedurę** nie musi być na podkładzie mapy zasadniczej. 
Procedura wygląda z reguły następująco:
1.	Uchwała wszczynająca z granicą (nie ma wymagania mapy)  - na tym etapie tworzymy pierwsze APP
2.	Etap zbierania danych, wniosków, w tym pozyskanie podkładów mapowych
3.	Tworzenie planu + uzgodnienia i dalszy etap…..
...
Do uchwały wszczynającej musimy w ciągu 30 dni zrobić APP, w tym czasie nie ma jeszcze podkładów, stąd należałoby to rozróżnić.

**Comment by KasiaZagrobelna** [comment]
Pani Moniko,
jak wskazałam wyżej - są to informacje o tym podkładzie mapowym, który został przez Panią wykorzystany. Wpisuje pani w tym polu zatem informacje o tym podkładzie mapowym/ mapie/ treści, z której pani korzystała.

Dodatkowo prosiłabym, by pytania, które nie dotyczą zgłoszeń błędów we wtyczce kierować poprzez formularz kontaktowy na stronie, bądź na adres mailowy -> upraszcza nam to odpowiadanie na Państwa pytania.

Pozdrawiam,

**Comment by 123MR123** [comment]
Przykro mi, że się nie rozumiemy.

Poprzednie zgłoszenie wysyłałam przez git-hub, może macie coś źle skonfigurowane, że trafiają do Pani.

Jednocześnie chyba Państwo nie rozróżniają uchwały intencyjnej od uchwały kończącej procedurę. 

Uchwała intencyjna rozpoczyna procedurę, nie ma mapy zasadniczej, a w ciągu 30 dni od jej podjęcia musimy zrobić APP.
