### ISSUE TITLE
mulitipoligon ze stycznymi granicami

### ISSUE THREAD

**Issue by ireneuszwojcik** [envirosolutionspl/wtyczka_qgis_app#120]
Dzień dobry wszystkim,
Mam bardzo ciekawy przypadek, mianowicie mam uchwałę o przystąpieniu do mpzp która obejmuje 4 obszary, te obszary są styczne ze sobą (mają wspólną granicę z jedną lub więcej). QGIS ma problem z połączeniem takiej warstwy w mulitipoligon i łączy je w jeden obszar. Wygląda że aby stworzyć multipoligon muszą być poligony które nie posiadają wspólnych punktów.
Próbowałem funkcji grupuj, po wykonaniu mamy mulitipoligon, ale nie przechodzi walidacji w aplikacji APP, a po użyciu funkcji napraw geometrię ginie część podziałów, obiekty są złączone.
Moje pytanie co w takiej sytuacji będzie prawidłowym postępowaniem dołączenie jednej granicy czy stworzenie 4 plików GML dla każdego obszaru osobno?
pozdrawiam
Irek Wójcik

**Comment by KasiaZagrobelna** [comment]
Panie Irku,
To są pytania, które nie dotyczą błędów we wtyczce. Proszę, by kierować je poprzez formularz kontaktowy na stronie, bądź na adres mailowy, bądź przez telefon -> upraszcza nam to odpowiadanie na Państwa pytania.

Pozdrawiam,
