### ISSUE TITLE
DokumentyFormalne z relacją "inne" (rola asocjacyjna dokument) - błąd wyświetlania z GML dla APP

### ISSUE THREAD

**Issue by KasiaZagrobelna** [envirosolutionspl/wtyczka_qgis_app#121]
Przy składaniu pliku GML dla pojedynczego APP  formularze dla dokumentów formalnych z relacją "inne" (rola asocjacyjna "dokument") nie są widoczne w pliku GML. 
Jedyny ślad w pliku GML to odniesienie w fragmencie <app:dokument xlink:href=...>, natomiast brak jest 
pozostałych atrybutów w ramach klasy <app:DokumentFormalny> jak ma to miejsce dla dokumentów
przystępujących i uchwalających.

W załączeniu przykład formularzy cząstkowych + przykład generowanego GMLa - brak w nim m.in. Dokumentu Formalnego dla oceny aktualności suikzp.
[GML suikzp + pojedyncze formularze_v1.1.zip](https://github.com/envirosolutionspl/wtyczka_qgis_app/files/5724565/GML.suikzp.%2B.pojedyncze.formularze_v1.1.zip)

**Comment by ksedron** [comment]
Błąd poprawiony, dokumenty formalne z relacją "inna" są już dodawane do pliku GML.

**Comment by KasiaZagrobelna** [comment]
Sprawdzone - działa.

**Comment by KasiaZagrobelna** [comment]
Poprawka będzie uwzględniona w v.1.1.2
