### ISSUE TITLE
błąd: No module named 'lxml'

### ISSUE THREAD

**Issue by karol-leszczynski** [envirosolutionspl/wtyczka_qgis_app#130]
Zainstalowałem wczoraj wtyczkę w qGis 3.2.3 przez managera wtyczek, od razu rzuciło błędem: No module named 'lxml'.
Wychodzi na to, że wtyczka korzysta z biblioteki, która nie jest składnikiem phytona dostarczanym wraz z qGis (a przynajmniej w
wersji 3.2.3). Rozwiązanie nie jest skomplikowane i polega na doinstalowaniu biblioteki za pomocą poleceń w skrypcie pip. Niemniej jednak nie każdy użytkownik wie jak używać wiersza poleceń (obstawiam, że 99.8% pracuje w windowsie) i nie każdy zna angielski na tyle żeby doczytać na czym polega problem. Nie znam pythona, ale jeśli to możliwe, to może warto rozpakować klasę z biblioteki i zostawić ją w kodzie wtyczki, lub dorzucić jakiś skrypt który dociągałby to co trzeba. Pozdrawiam!

**Comment by KasiaZagrobelna** [comment]
Panie Karolu, dedykowanymi wersjami QGIS dla Wtyczki APP są wersje powyżej 3.10 (co jest też wskazane w jej opisie). 
Używanie starszych wersji może skutkować tego typu błędami, zatem zalecam korzystać z wersji QGIS powyżej 3.10.

**Comment by envirosolutionspl** [comment]
@KasiaZagrobelna sugeruję ustawienie minimalnej wersji QGIS dla której wtyczka jest wspierana na 3.10, wtedy nie będzie możliwości pobrania z menadżera wtyczek narzędzia APP dla starszych wersji QGIS

**Comment by KasiaZagrobelna** [comment]
> 
> 
> @KasiaZagrobelna sugeruję ustawienie minimalnej wersji QGIS dla której wtyczka jest wspierana na 3.10, wtedy nie będzie możliwości pobrania z menadżera wtyczek narzędzia APP dla starszych wersji QGIS

Ok, to zmieniam w metadanych na "qgisMinimumVersion=3.10"

**Comment by KasiaZagrobelna** [comment]
@karol-leszczynski - wprowadzono ograniczenie do min. wersji QGIS w nowej wersji wtyczki - 1.1.4. Proszę o sprawdzenie, czy wszystko działa.

**Comment by KasiaZagrobelna** [comment]
Ze względu na brak odpowiedzi - zakładam, że wszystko działa i zamykam wątek.
