### ISSUE TITLE
Walidator nie wykrywa błędu w wersjonowaniu Dokumentów Formalnych

### ISSUE THREAD

**Issue by KasiaZagrobelna** [envirosolutionspl/wtyczka_qgis_app#132]
Korekta walidatora w zakresie weryfikacji ograniczenia _obiektWersjonowany_ dla obiektów typu _DokumentFormalny_ (weryfikacja czy dla tych obiektów istnieje IdWersji i komunikowanie o tym błędu).
Zgłoszenie powiązane z poprawą błędu #124, gdzie dotyczyło to dokumentów suikzp i pzpw.

**Comment by envirosolutionspl** [comment]
@KasiaZagrobelna proszę o uszcegółowieniu problemu. Co konkretnie powinno być weryfikowane dla dokumentów formalnych?

**Comment by KasiaZagrobelna** [comment]
Walidator powinien sprawdzać, czy dla obiektów typu DokumentFormalny występuje atrybut <app:wersjaId>. 
W przypadku wykrycia atrybutu powinien oznaczyć to jako błąd i wyrzucić komunikat:
"Instancje typu obiektu DokumentFormalny nie mogą być wersjonowane."

**Comment by KasiaZagrobelna** [comment]
Uwzględnione w v.1.2.0. Zamykam.
