### ISSUE TITLE
Za mała dokładność czasowa pól poczatekWersjiObiektu i koniecWersjiObiektu

### ISSUE THREAD

**Issue by Gor1nV** [envirosolutionspl/wtyczka_qgis_app#140]
Zgodnie z pkt 2.1 Załącznika nr 1 do  Rozporządzenia Ministra Rozwoju, Pracy i Technologii z dnia 26 października 2020 r. w sprawie zbiorów danych przestrzennych oraz metadanych w zakresie zagospodarowania przestrzennego (Dz. U. 2020 r. poz. 1916) dziedziną pola poczatekWersjiObiektu i koniecWersjiObiektu jest "DataCzas będący połączeniem daty (opisanej wartościami dla roku, miesiąca i dnia) i czasu (opisanego godziną, minutą i _**sekundą**_)." Jednak Wtyczka APP w wersji 1.1.4 nie pozwala na ręczne wprowadzenie sekund we wspomnianych wyżej polach, pomimo tego, że są one wyświetlane w polu "wersjaId*".
![image](https://user-images.githubusercontent.com/86721161/123953947-1d0c2380-d9a8-11eb-82d2-f6ae40d585fa.png)

Otrzymałem dane przestrzenne o wartości pola koniecWersjiObiektu z dokładnością do sekundy i tworząc ich kolejną wersję APP muszę w polu poczatekWersjiObiektu wprowadzić wartość odpowiadającą końcowi wersji obiektu poprzeniego. Nie mogę tego jednak zrobić, bo wtyczka na to nie pozawala. 
Proszę o zwiększenie dokładności czasowej we Wtyczce APP pól poczatekWersjiObiektu i koniecWersjiObiektu do sekund.

**Comment by KasiaZagrobelna** [comment]
Poprawka uwzględniona w wersji 1.2.0. Wtyczki APP.

**Comment by KasiaZagrobelna** [comment]
W związku z poprawką -> otrzymaliśmy od użytkownika zgłoszenie mailowe o błędzie. 
Wklejam poniżej treść zgłoszenia oraz załączone do niego pliki: 

"Dzień dobry,
w nawiązaniu do rozmowy, przesyłamy w załączeniu screen błędu Wtyczki APP po aktualizacji tejże do wersji 1.2.0. z przykładowym formularzem pierwotnie zapisanym w poprzedniej wersji Wtyczki. Błędy Pythona dotyczą daty "początek wersji obiektu", tzn. poziomu sekundnika tej daty (w formularzu jest niby w porządku, sekundnik się zmienia - jak w przykładzie - jednakże po jego zapisaniu i chęci przejścia do kroku 3. wyrzuca błąd jak na screenie, że brakuje... sekundnika).
Błąd można pominąć pozostawiając pusty formularz i od razu przechodząc do kroku 3. (ale to jest naokoło). Formularz nie był zmieniany od poprzedniej wersji Wtyczki.
Wersja Qgis jak w opisie błędu, Windows 10 64 bit."
![blad Pythona Wtyczka APP](https://user-images.githubusercontent.com/47556554/128008774-4100d302-6f7c-4067-9fcf-6cf5fba4696c.png)

**Comment by KasiaZagrobelna** [comment]
[rys.1.xml.zip](https://github.com/envirosolutionspl/wtyczka_qgis_app/files/6923717/rys.1.xml.zip)

W związku z powyższym -> drugi z załączonych do zgłoszenia plików.

**Comment by KasiaZagrobelna** [comment]
Dziękuję za szybką poprawę błędu — błąd opisany powyżej już nie występuje.

**Comment by KasiaZagrobelna** [comment]
Pojawił się za to kolejny błąd w dacie — przy pobieraniu wartości z istniejącego formularza w kroku 5 z 6 Wtyczki APP (wcześniej nie występował), wyświetla się komunikat o błędzie, który przesyłam poniżej:
![Zrzut ekranu 2021-08-10 102314](https://user-images.githubusercontent.com/47556554/128834696-dfd32f5d-7cee-40a7-b6a5-e90b336c9441.jpg)

**Comment by KasiaZagrobelna** [comment]
[app1.zip](https://github.com/envirosolutionspl/wtyczka_qgis_app/files/7224600/app1.zip)
Dodaję plik, po którego wczytaniu wyskakuje ten błąd.

**Comment by KasiaZagrobelna** [comment]
Poprawka błędu uwzględniona w wersji 1.2.1.
