### ISSUE TITLE
Błąd w wersji 2

### ISSUE THREAD

**Issue by 123MR123** [envirosolutionspl/wtyczka_qgis_app#142]
1.Po zaktualizowaniu wtyczki do wersji 2, wtyczka zacina się po zapisaniu pierwszego formularza. Nie ma możliwości przejścia dalej, trzeba zrestartować program.
2. W formularzu dokumentów formalnych nie można pobierać danych z formularza app  - wyłącznie z formularza rysunku, ponieważ wyskakuje błąd.

**Comment by KasiaZagrobelna** [comment]
@123MR123, czy mogłabym prosić o zrzuty ekranów ze wspomnianymi błędami?

**Comment by 123MR123** [comment]
1.       W formularzu dokumentu formalnego po próbie wczytania formularza app :



2.       Po zapisaniu formularza rysunku zawiesza się wtyczka, nie ma możliwości przejścia do kolejnego formularza, trzeba zrestartować program.

Mam jeszcze pytanie, jak zaktualizować gml jeśli nie mamy formularzy tak aby na nowo nie wprowadzać wszystkich danych?

**Comment by KasiaZagrobelna** [comment]
@123MR123 Nie widzę zrzutu co do problemu 1, mogłabym prosić o dodanie jeszcze raz. 
Co do problemu 2 - czy ekran z błędem jest taki sam jak w  wątku #140 (https://github.com/envirosolutionspl/wtyczka_qgis_app/issues/140#issuecomment-895837822) ?

**Comment by 123MR123** [comment]
Witam, przesyłam w załącznikach.

**Comment by envirosolutionspl** [comment]
@123MR123 proszę spróbować na wersji "master"

**Comment by 123MR123** [comment]
skąd pobrać wersje master?
zrzuty wysyłałam mailem

**Comment by KasiaZagrobelna** [comment]
1. W zakładce Code należy nacisnąć przycisk Code -> Download zip. 
2. Zmienić nazwę folderu i zipa usuwając dopisek master na końcu.
3. W QGIS wybrać instalację Wtyczki z pliku zip i wskazać "wtyczka_qgis_app.zip".

Edit: Oczywiście najpierw należy odinstalować poprzednią wersję Wtyczki :)

**Comment by KasiaZagrobelna** [comment]
@123MR123 
> zrzuty wysyłałam mailem

Musiał Pan/Pani odpowiadać na automatyczne powiadomienia z githuba o zmianach w obserwowanych wątkach. :)
Proszę kolejnym razem dodawać zrzuty poprzez przeciągnięcie pliku jpg do odpowiedzi w wątku — wtedy będą się pojawiać w odpowiednim zgłoszeniu.

**Comment by 123MR123** [comment]
Dokładnie odpisywałam na maila.
Pobrałam wtyczkę, przetestuję.

**Comment by 123MR123** [comment]
Przy próbie instalacji otrzymałam poniższy błąd

![Przechwytywanie](https://user-images.githubusercontent.com/75789281/135421259-3dc9dfca-4dd6-4f97-abe6-c92891ccd44d.JPG)

**Comment by KasiaZagrobelna** [comment]
@123MR123 Proszę spróbować jeszcze raz z uwzględnieniem punktu 2, tzn. Przy instalacji z pliku zip proszę się upewnić, że zarówno zip, jak i folder wewnątrz niego nie mają dopisku "-master".

**Comment by KasiaZagrobelna** [comment]
Poprawka błędu uwzględniona w wersji 1.2.1. Zamykam.
