### ISSUE TITLE
Fatal error podczas wychodzenia z projektu bez zapisywania zmian

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/wtyczka_qgis_app#154]
Podczas wychodzenia z projektu, nie zapisując tych warstw, ponownie próbuję otworzyć projekt i otrzymuję poniższy komunikat:
![image](https://github.com/envirosolutionspl/wtyczka_qgis_app/assets/113895660/92eeca6b-b72a-4e58-8cef-6ce70edf30e9)

**Comment by KasiaZagrobelna** [comment]
Dzień dobry — w najnowszej wersji 2.0.3 (experimental) zostały wprowadzone poprawki m.in. dot. stabilności Wtyczki . Najnowsza wersja jest dostępna tutaj: https://github.com/CyfryzacjaAPP/wtyczka_qgis_app_2 - jeśli błąd dalej występuje, proszę o zgłoszenie błędu już w nowym repozytorium github.
