### ISSUE TITLE
Błędne sprawdzanie granicy gminy

### ISSUE THREAD

**Issue by 123MR123** [envirosolutionspl/wtyczka_qgis_app#156]
Wtyczka błędnie sprawdza granice państwa. Dla gmin, które leżą przy granicy państwa nie można zrobić gml dla POG. Wtyczka wyrzuca błąd - granica leży poza graniami kraju.  Moim zdaniem można dodać bufor 1000m przy sprawdzaniu, pomiary geodezyjne często się zmieniają i problem będzie występował w wielu gminach. Poza tym granica Państwa z PRG nie jest tożsama z granicami geodezyjnymi, występują i będą występować przesunięcia a taka restrykcyjna blokada uniemożliwia pracę we wtyczce.

**Comment by KasiaZagrobelna** [comment]
Dzień dobry, w wersjach Wtyczki 2.0.3 (experimental) i powyżej jest już uwzględniony kilkucentymetrowy bufor dla kontroli spójności POG względem granicy Polski (m.in. w odpowiedzi na zgłoszenia przygranicznych gmin). Wskazany przez Pana do wprowadzenia bufor 1 km sprawiałby, że ta kontrola byłaby bezprzedmiotowa.

**Comment by 123MR123** [comment]
Korzystam z najnowszej wtyczki. Granica Państwa z PRG ma kilkudziesięciometrowe błędy do granic geodezyjnych, przez takie kontrole nie możemy zrobić plików GML.

**Comment by 123MR123** [comment]
Granice geodezyjne to ogromny problem na terenie całego kraju,  one zmieniają się niezależnie od gmin, proszę zasięgnąć opinii fachowców i prosimy jednak o zwiększenie sprawdzanych buforów, ponieważ gminy będą miały poważny problem. Jeden z największych błędów jest w gminie Bogatynia, proponuję przeanalizować, mogę również przesłać granice geodezyjne gmin, jeśli chcą Państwo porównać. Sprawdziłam w szybkiej analizie znalazłam błąd ponad 8m (gmina Bogatynia), choć nie szukałam dokładnie.

**Comment by KasiaZagrobelna** [comment]
W takim razie przeanalizujemy jeszcze raz problem. Byłabym wdzięczna za podesłanie plików na email: cyfryzacja.app@mrit.gov.pl - by porównać, jak duże rozbieżności występują.
