### ISSUE TITLE
Lokalizacja obiektów - ReferenceType

### ISSUE THREAD

**Issue by ksedron** [envirosolutionspl/wtyczka_qgis_app#96]
Gdzie będą przechowywane obiekty typu ReferenceType? 
Nie została określona zmiana lokalizacji obiektów - brak zmian?

Aktualnie:
`<app:dokumentPrzystepujacy xlink:href="http://zagospodarowanieprzestrzenne.gov.pl/app/DokumentFormalny/PL.ZIPPZP.2/14-PZPW/DOC2"/>`

**Comment by Ba-si** [comment]
Zmienione na:
https://www.gov.pl/static/zagospodarowanieprzestrzenne
zamiast:
https://www.gov.pl/zagospodarowanieprzestrzenne

zbędne słowo "**static**" przy id obiektu.
Dla identyfikacji schematu i list kodowych "static" nadal ma występować.

**Comment by envirosolutionspl** [comment]
zrobione - do sprawdzenia

**Comment by KasiaZagrobelna** [comment]
Zweryfikowane - jest ok. Można zamknąć.
